[project]
name = "summer-tech-camp2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"

dependencies = [
    "colorama",
    "exceptiongroup",
    "google-cloud-speech",
    "google-cloud-texttospeech",
    "grpcio-status",
    "gTTS",
    "openai==2.8.0", # Pinned, as v3+ is a different API
    "PyQt5",
    "QtAwesome",
    "miniaudio>=1.59",
    "faster-whisper>=1.0.0",
    "pydub>=0.25.1",
    "numpy",
]
